services:
  db:
    image: postgres:15-alpine
    container_name: backend-go-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13252021aigerim
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:13252021aigerim@db:5432/events?sslmode=disable",
      "up"
    ]

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"

  app:
    build: .
    container_name: backend-go-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      notification-service:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 13252021aigerim
      DB_NAME: events
      DB_PORT: 5432
      NOTIFICATION_SERVICE_URL: http://notification-service:8085

volumes:
  postgres_data: